//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// CLCL.rc で使用
//
#define IDS_MENU_REGIST                 1
#define IDS_MENU_CANCEL                 2
#define IDS_MENU_EXIT                   3
#define IDS_MENU_VIEWER                 4
#define IDS_MENU_OPTION                 5
#define IDS_MENU_CLIPBOARD_WATCH        6
#define IDS_TREEITEM_CLIPBOARD          10
#define IDS_TREEITEM_HISTORY            11
#define IDS_TREEITEM_REGIST             12
#define IDS_TREEITEM_NEWFOLDER          13
#define IDS_LISTCOLUMN_DATA             20
#define IDS_LISTCOLUMN_SIZE             21
#define IDS_LISTCOLUMN_DATE             22
#define IDS_LISTCOLUMN_WINDOW           23
#define IDS_LISTCOLUMN_HOTKEY           24
#define IDI_ICON_MAIN                   50
#define IDI_ICON_CLIP                   51
#define IDI_ICON_CLIP_BAN               52
#define IDI_ICON_CLIPBOARD              53
#define IDI_ICON_DEFAULT                54
#define IDI_ICON_TEXT                   55
#define IDI_ICON_REGIST                 56
#define IDI_ICON_BITMAP                 57
#define IDI_ICON_FILE                   58
#define IDS_ERROR_END                   100
#define IDS_ERROR_HOTKEY                101
#define IDS_ERROR_WINDOW_INIT           102
#define IDR_MENU_POPUP                  103
#define IDS_ERROR_FILENAME              103
#define IDS_ERROR_FOLDERNAME            104
#define IDR_MENU_VIEWER                 107
#define IDC_CURSOR_SEP                  113
#define IDR_ACCELERATOR                 115
#define IDD_DIALOG_SELECT_FOLDER        118
#define IDC_CURSOR_MOVE                 119
#define IDC_CURSOR_BAN                  120
#define IDC_CURSOR_COPY                 122
#define IDR_TOOLBAR                     126
#define IDD_DIALOG_SELECT_FORMAT        128
#define IDD_DIALOG_SET_HOTKEY           133
#define IDI_ICON1                       135
#define IDI_ICON_FOLDER                 135
#define IDR_TOOLBAR32                   136
#define IDR_TOOLBAR2                    138
#define IDR_TOOLBAR48                   138
#define IDS_QUESTION_DELETE             200
#define IDS_QUESTION_REPLACE            201
#define IDS_DIALOG_ADDPOS               300
#define IDS_DIALOG_COPYPOS              301
#define IDS_DIALOG_MOVEPOS              302
#define IDS_DIALOG_IMPORT               303
#define IDS_DIALOG_EXPORT               304
#define IDS_VIEWER_COPYNAME             400
#define IDS_VIEWER_COPYNAME_NUM         401
#define IDS_VIEWER_MENU_TOOL_NOTHING    402
#define IDS_STATUSBAR_ITEM_CNT          500
#define IDS_STATUSBAR_BYTES             501
#define IDS_STATUSBAR_KB                502
#define IDS_BIN_MENU_UNDO               600
#define IDS_BIN_MENU_REDO               601
#define IDS_BIN_MENU_LOCK               602
#define IDS_BIN_MENU_FONT               603
#define IDS_TEXT_MENU_UNDO              700
#define IDS_TEXT_MENU_REDO              701
#define IDS_TEXT_MENU_CUT               702
#define IDS_TEXT_MENU_COPY              703
#define IDS_TEXT_MENU_PASTE             704
#define IDS_TEXT_MENU_DELETE            705
#define IDS_TEXT_MENU_SELECT_ALL        706
#define IDS_TEXT_MENU_WORDWRAP          707
#define IDS_TEXT_MENU_SELECT_FONT       708
#define IDS_BITMAP_MENU_STRETCH         800
#define IDS_BITMAP_MENU_ZOOM_IN         801
#define IDS_BITMAP_MENU_ZOOM_OUT        802
#define IDS_FILE_LIST_NAME              900
#define IDS_FILE_LIST_FOLDER            901
#define IDS_FILE_LIST_TYPE              902
#define IDS_FILE_LIST_TYPE_DEF          903
#define IDS_FILE_MENU_OPEN              904
#define IDS_FILE_MENU_ADD               905
#define IDS_FILE_MENU_DELETE            906
#define IDS_FILE_DELETE_MSG             907
#define IDS_FILE_MENU_COPY_FILE         908
#define IDS_FILE_MENU_COPY_PATH         909
#define IDC_TREE                        1000
#define IDC_STATIC_MSG                  1001
#define IDC_COMBO_FORMAT                1002
#define IDC_EDIT_FILE                   1003
#define IDC_BUTTON_FILE_SELECT          1004
#define IDC_CHECK_FILE_READ             1005
#define IDC_STATIC_FILE                 1006
#define IDC_HOTKEY_ITEM                 1007
#define IDC_CHECK_PASTE                 1008
#define IDC_CHECK_WIN                   1009
#define ID_MENUITEM_EXIT                40001
#define ID_MENUITEM_VIEWER              40002
#define ID_MENUITEM_OPTION              40003
#define ID_MENUITEM_CLOSE               40004
#define ID_MENUITEM_CLIPBOARD_WATCH     40005
#define ID_ACCEL_CTRL_TAB               40008
#define ID_MENUITEM_DELETE              40009
#define ID_MENUITEM_CLIPBOARD           40010
#define ID_MENUITEM_CREATE_FOLDER       40012
#define ID_MENUITEM_REGIST_ADD          40013
#define ID_MENUITEM_RENAME              40014
#define ID_MENUITEM_UP                  40015
#define ID_MENUITEM_DOWN                40016
#define ID_MENUITEM_SELECT_ALL          40017
#define ID_MENUITEM_SHOW_BIN            40018
#define ID_MENUITEM_CLEAR_NAME          40019
#define ID_MENUITEM_REGIST_MOVE         40020
#define ID_MENUITEM_SAVE                40022
#define ID_MENUITEM_SHOW_FORMAT         40023
#define ID_BUTTON40024                  40024
#define ID_BUTTON40025                  40025
#define ID_BUTTON40026                  40026
#define ID_BUTTON40027                  40027
#define ID_MENUITEM_ABOUT               40028
#define ID_MENUITEM_SHOW_TOOLBAR        40029
#define ID_MENUITEM_SHOW_STATUSBAR      40030
#define ID_MENUITEM_NEW_ITEM            40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40034                  40034
#define ID_MENUITEM_DATA_SAVE           40036
#define ID_MENUITEM_WATCH               40037
#define ID_MENUITEM_SET_FORMAT          40041
#define ID_MENUITEM_SET_FILTER          40042
#define ID_MENUITEM_TOOL_SET            40044
#define ID_MENUITEM_TOOL_MENU           40045
#define ID_MENUITEM_PASTE               40048
#define ID_BUTTON40049                  40049
#define ID_MENUITEM_IMPORT              40050
#define ID_MENUITEM_EXPORT              40051
#define ID_MENUITEM_SET_HOTKEY          40053
#define ID_MENUITEM_OPEN                40054
#define ID_MENU_DGDP_MOVE               40063
#define ID_MENU_DGDP_COPY               40064
#define ID_MENUITEM_CLIPBOARD_TB        50000
#define ID_MENUITEM_PASTE_TB            50001
#define ID_MENUITEM_REGIST_ADD_TB       50002
#define ID_MENUITEM_NEW_ITEM_TB         50003
#define ID_MENUITEM_DELETE_TB           50004
#define ID_MENUITEM_UP_TB               50005
#define ID_MENUITEM_DOWN_TB             50006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
