; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CLCL"
#define MyAppVersion "2.1.6.0"
#define MyAppPublisher "WilfZim"
#define MyAppURL "https://www.linguversa.de/clcl/index.html"
#define MyGitHubRepo "https://github.com/wilfz/CLCL"
#define MyAppExeName "CLCL.exe"

#define ToolClipGitHubRepo "https://github.com/wilfz/CLCL-tool_clip" 

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{ECD230BD-947E-4F83-A975-74AD73FB420C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf32}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=auto
AllowNoIcons=yes
LicenseFile=LICENSE
InfoBeforeFile=installation_info.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=Setup
OutputBaseFilename=setup_clcl
;SetupIconFile=res\icon1.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "full"; Description: "Full installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "main"; Description: "CLCL main program"; Types: full custom;
Name: "help"; Description: "HTML Help Files"; Types: full
Name: "tool_text"; Description: "Plugin for text manipulation"; Types: full
Name: "tool_utl"; Description: "Plugin with other utilities"; Types: full
Name: "tool_clip"; Description: "Plugin by WilfZim"; Types: full
Name: "tool_test"; Description: "Example plugin"; Types: full
Name: "fmt_rtf"; Description: "Format plugin for RichTextFormat"; Types: full
Name: "readme"; Description: "ReadMe"; Types: full
;Name: "readme\en"; Description: "English"; Flags: exclusive
;Name: "readme\jp"; Description: "Japanese"; Flags: exclusive

[Files]
Source: "Release\{#MyAppExeName}"; DestDir: "{app}"; Components: main; Flags: ignoreversion
Source: "Release\CLCLSet.exe"; DestDir: "{app}"; Components: main; Flags: ignoreversion
Source: "Release\CLCLHook.dll"; DestDir: "{app}"; Components: main; Flags: ignoreversion
Source: "Documentation\clcl.chm"; DestDir: "{app}"; Components: main help; Flags: ignoreversion
Source: "Documentation\clcl_de.chm"; DestDir: "{app}"; Components: main help; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Components: main; Flags: ignoreversion
Source: "clcl_app.ini"; DestDir: "{app}"; Components: main; Flags: ignoreversion
Source: "CLCLPlugin\tool_test\Release\tool_test.dll"; DestDir: "{app}"; Components: tool_test; Flags: ignoreversion
Source: "CLCLPlugin\tool_text\Release\tool_text.dll"; DestDir: "{app}"; Components: tool_text; Flags: ignoreversion
Source: "CLCLPlugin\tool_utl\Release\tool_utl.dll"; DestDir: "{app}"; Components: tool_utl; Flags: ignoreversion
Source: "CLCLPlugin\tool_clip\Release\tool_clip.dll"; DestDir: "{app}"; Components: tool_clip; Flags: ignoreversion
Source: "CLCLPlugin\fmt_rtf\Release\fmt_rtf.dll"; DestDir: "{app}"; Components: fmt_rtf; Flags: ignoreversion
Source: "readme_en.txt"; DestDir: "{app}"; Components: readme; Flags: ignoreversion 
Source: "readme_jp.txt"; DestDir: "{app}"; Components: main help readme; Flags: ignoreversion
Source: "readme_en.txt"; DestDir: "{app}"; Components: readme; Languages: english german ukrainian; Flags: ignoreversion isreadme
Source: "readme_jp.txt"; DestDir: "{app}"; Components: readme; Languages: japanese; Flags: ignoreversion isreadme
Source: "Release\clcl.html"; DestDir: "{app}"; Components: help; Flags: ignoreversion
Source: "CLCLPlugin\tool_clip\Release\tool_clip.html"; DestDir: "{app}"; Components: tool_clip; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[INI]
;Filename: "{app}\clcl_app.ini"; Section: "GENERAL"; Key: "language"; Languages: english; String: "en";
;Filename: "{app}\clcl_app.ini"; Section: "GENERAL"; Key: "language"; Languages: japanese; String: "ja";
;Filename: "{app}\clcl_app.ini"; Section: "GENERAL"; Key: "language"; Languages: german; String: "de";
;Filename: "{app}\clcl_app.ini"; Section: "GENERAL"; Key: "language"; Languages: ukrainian; String: "uk";

[Icons]
; Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#MyAppName} - Clipboard Tool"; Filename: "{app}\{#MyAppExeName}"; Parameters: "/v"
Name: "{group}\{#MyAppName}'s Website"; Filename: "{#MyAppURL}"
Name: "{group}\{#MyAppName} on GitHub"; Filename: "{#MyGitHubRepo}"
Name: "{group}\{#MyAppName} Help"; Filename: "{app}\clcl.chm"; Components: main help
;Name: "{group}\ReadMe"; Filename: "{app}\readme_jp.txt"
Name: "{group}\Tool_Clip Help"; Filename: "{app}\tool_clip.html"; Components: tool_clip
Name: "{group}\Tool_Clip on GitHub"; Filename: "{#ToolClipGitHubRepo}"; Components: tool_clip
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "/v"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "/v"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

