//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CLCLSet.rc
//
#define IDS_MENU_REGIST                 1
#define IDS_MENU_CANCEL                 2
#define IDS_MENU_EXIT                   3
#define IDS_MENU_VIEWER                 4
#define IDS_MENU_OPTION                 5
#define IDS_MENU_CLIPBOARD_WATCH        6
#define IDS_TREEITEM_REGIST             12
#define IDD_DIALOG_HISTORY              101
#define IDD_DIALOG_ACTION               102
#define IDD_DIALOG_ACTION_SET           103
#define IDD_DIALOG_SELECT_ICON          104
#define IDI_ICON_MAIN                   105
#define IDD_DIALOG_SELECT_FOLDER        106
#define IDI_ICON_REGIST                 107
#define IDD_DIALOG_MENU                 110
#define IDD_DIALOG_VIEWER               111
#define IDD_DIALOG_FORMAT               113
#define IDD_DIALOG_FORMAT_SET           114
#define IDD_DIALOG_SELECT_FUNC          115
#define IDD_DIALOG_FORMAT_PROP          116
#define IDD_DIALOG_FILTER               117
#define IDD_DIALOG_FILTER_SET           118
#define IDD_DIALOG_WINDOW               119
#define IDD_DIALOG_WINDOW_SET           120
#define IDD_DIALOG_SENDKEY              121
#define IDD_DIALOG_SENDKEY_SET          122
#define IDD_DIALOG_TOOL                 123
#define IDD_DIALOG_TOOL_SET             124
#define IDC_LIST_ACTION                 1000
#define IDC_TREE                        1000
#define IDS_OPTION_TITLE                1000
#define IDC_BUTTON_ADD                  1001
#define IDS_OPTION_START_ERROR          1001
#define IDC_BUTTON_EDIT                 1002
#define IDS_OPTION_DELETE               1002
#define IDC_BUTTON_DELETE               1003
#define IDC_BUTTON_PROP                 1004
#define IDC_BUTTON_COPY                 1004
#define IDC_COMBO_ACTION                1006
#define IDC_COMBO_TYPE                  1007
#define IDC_HOTKEY                      1008
#define IDC_COMBO_CONTENT               1010
#define IDC_EDIT_TITLE                  1011
#define IDC_EDIT_ICON_FILE              1012
#define IDC_EDIT_CMD_LINE               1012
#define IDC_BUTTON_ICON_FILE_SELECT     1013
#define IDC_EDIT_ICON_INDEX             1014
#define IDC_EDIT_PATH                   1015
#define IDC_BUTTON_PATH_SELECT          1016
#define IDC_EDIT_CMD                    1017
#define IDC_EDIT_MAX                    1018
#define IDC_EDIT_MIN                    1019
#define IDC_BUTTON_UP                   1021
#define IDC_BUTTON_DOWN                 1022
#define IDC_CHECK_ENABLE                1024
#define IDC_TREE_MENU                   1025
#define IDC_CHECK_PASTE                 1026
#define IDC_EDIT_ADD_INTERVAL           1027
#define IDC_CHECK_CARET                 1028
#define IDC_CHECK_SAVE                  1029
#define IDC_CHECK_ALWAYS_SAVE           1030
#define IDC_CHECK_DELETE                1031
#define IDC_RADIO_CHECK_NO              1032
#define IDC_RADIO_CHECK_ONE             1033
#define IDC_CHECK_SHOW_ICON             1033
#define IDC_RADIO_CHECK_ALL             1034
#define IDC_CHECK_SHOW_BITMAP           1034
#define IDC_CHECK_SHOW_TOOLTIP          1035
#define IDC_RADIO_CHECK_ALL_DELETE      1035
#define IDC_EDIT_SHOW_DELAY             1036
#define IDC_CHECK_IGNORE_REGIST_ITEM    1036
#define IDC_CHECK_BREAK                 1037
#define IDC_EDIT_MAX_WIDTH              1038
#define IDC_EDIT_TEXT_FORMAT            1039
#define IDC_BUTTON_FORMAT_SELECT        1040
#define IDC_CHECK_TOGGLE                1041
#define IDC_CHECK_SHOW_TOOL_MENU        1041
#define IDC_CHECK_CLIP_EXPAND           1042
#define IDC_CHECK_SHOW_HOTKEY           1042
#define IDC_CHECK_HISTORY_EXPAND        1043
#define IDC_EDIT_ICON_SIZE              1043
#define IDC_CHECK_REGIST_EXPAND         1044
#define IDC_LIST_FROM                   1046
#define IDC_LIST_TO                     1047
#define IDC_CHECK_FOLDER_EXPAND         1048
#define IDC_CHECK_GENERAL               1049
#define IDC_LIST_FORMAT                 1050
#define IDC_EDIT_FORMAT_NAME            1052
#define IDC_EDIT_LIB_PATH               1053
#define IDC_EDIT_HEADER                 1054
#define IDC_BUTTON_FILE_SELECT          1055
#define IDC_BUTTON_FUNC_SELECT          1056
#define IDC_LIST_HEADER                 1057
#define IDC_EDIT_TOOLTIP_SIZE           1058
#define IDC_EDIT_BMP_WIDTH              1059
#define IDC_EDIT_BMP_HEIGHT             1060
#define IDC_BUTTON_BROWS                1062
#define IDC_LIST_FILTER                 1062
#define IDC_RADIO_ADD                   1063
#define IDC_RADIO_IGNORE                1064
#define IDC_EDIT_SIZE                   1065
#define IDC_RADIO_ALL_ADD               1066
#define IDC_RADIO_ALL_IGNORE            1067
#define IDC_LIST_WINDOW                 1068
#define IDC_EDIT_CLASSNAME              1070
#define IDC_BUTTON_SELECT               1071
#define IDC_BUTTON_RELOAD               1072
#define IDC_LIST_SENDKEY                1073
#define IDC_HOTKEY_COPY                 1074
#define IDC_HOTKEY_PASTE                1075
#define IDC_EDIT_PASTE_WAIT             1076
#define IDC_CHECK_NOSAVE                1077
#define IDC_EDIT_COPY_WAIT              1077
#define IDC_BUTTON_FORMAT               1078
#define IDC_LIST_TOOL                   1079
#define IDC_CHECK_MENU                  1080
#define IDC_CHECK_VIEWER                1081
#define IDC_CHECK_HISTORY               1082
#define IDC_CHECK_CLIPBOARD             1083
#define IDC_CHECK_START                 1084
#define IDC_CHECK_END                   1085
#define IDC_CHECK_OLD                   1086
#define IDC_STATIC_MSG                  1087
#define IDC_CHECK_VIEWER_OPEN           1087
#define IDC_HOTKEY_TOOL                 1088
#define IDC_CHECK_COPY_PATE             1089
#define IDC_CHECK_VIEWER_CLOSE          1090
#define IDC_STATIC_PATH                 1095
#define IDC_CHECK_IGNORE                1097
#define IDC_CHECK_FOCUS                 1098
#define IDC_SPIN_ICON_INDEX             1098
#define IDC_SPIN_MAX                    1099
#define IDC_SPIN_SIZE                   1100
#define IDC_SPIN_MIN                    1100
#define IDC_SPIN_TOOLTIP_SIZE           1102
#define IDC_SPIN_ADD_INTERVAL           1104
#define IDC_SPIN_ICON_SIZE              1105
#define IDC_SPIN_BMP_WIDTH              1106
#define IDC_SPIN_BMP_HEIGHT             1107
#define IDC_SPIN_SHOW_DELAY             1108
#define IDC_SPIN_MAX_WIDTH              1109
#define IDC_SPIN_COPY_WAIT              1110
#define IDC_SPIN_PASTE_WAIT             1111
#define IDC_RADIO_DEF_OPEN              1114
#define IDC_RADIO_DEF_CLIPBOARD         1115
#define IDC_RADIO_DEF_SAVE              1116
#define IDC_LIST_ICON                   1127
#define IDC_EDIT_FILE                   1128
#define IDS_MENU_FORMAT_1               2001
#define IDS_MENU_FORMAT_2               2002
#define IDS_MENU_FORMAT_3               2003
#define IDS_MENU_FORMAT_4               2004
#define IDS_MENU_FORMAT_5               2005
#define IDS_MENU_FORMAT_6               2006
#define IDS_MENU_FORMAT_7               2007
#define IDS_MENU_FORMAT_8               2008
#define IDS_MENU_FORMAT_9               2009
#define IDS_MENU_FORMAT_10              2010
#define IDS_MENU_FORMAT_11              2011
#define IDS_VIEWER_CLIPBOARD            3000
#define IDS_VIEWER_HISTORY              3001
#define IDS_VIEWER_REGIST               3002
#define IDS_ACTION_LIST_HEAD_ACTION     4000
#define IDS_ACTION_LIST_HEAD_TYPE       4001
#define IDS_ACTION_POPUPMEMU            4002
#define IDS_ACTION_VIEWER               4003
#define IDS_ACTION_OPTION               4004
#define IDS_ACTION_CLIPBOARD_WATCH      4005
#define IDS_ACTION_EXIT                 4006
#define IDS_ACTION_TYPE_HOTKEY          4007
#define IDS_ACTION_TYPE_CTRL_CTRL       4008
#define IDS_ACTION_TYPE_SHIFT_SHIFT     4009
#define IDS_ACTION_TYPE_ALT_ALT         4010
#define IDS_ACTION_TYPE_TRAY_LEFT       4011
#define IDS_ACTION_TYPE_TRAY_LEFT_DBLCLK 4012
#define IDS_ACTION_TYPE_TRAY_RIGHT      4013
#define IDS_ACTION_TYPE_TRAY_RIGHT_DBLCLK 4014
#define IDS_ACTION_CONTENT_SEPARATOR    4015
#define IDS_ACTION_CONTENT_HISTORY      4016
#define IDS_ACTION_CONTENT_HISTORY_DESC 4017
#define IDS_ACTION_CONTENT_REGIST       4018
#define IDS_ACTION_CONTENT_REGIST_DESC  4019
#define IDS_ACTION_CONTENT_POPUP        4020
#define IDS_ACTION_CONTENT_VIEWER       4021
#define IDS_ACTION_CONTENT_OPTION       4022
#define IDS_ACTION_CONTENT_CLIPBOARD_WATCH 4023
#define IDS_ACTION_CONTENT_TOOL         4024
#define IDS_ACTION_CONTENT_APP          4025
#define IDS_ACTION_CONTENT_CANCEL       4026
#define IDS_ACTION_CONTENT_EXIT         4027
#define IDS_ACTION_TREE_MENU            4028
#define IDS_ACTION_TREE_NEW             4029
#define IDS_ACTION_TREE_SEP             4030
#define IDS_ACTION_ERR_ACTION           4031
#define IDS_ACTION_ERR_TYPE             4032
#define IDS_ACTION_TYPE_NOTHING         4033
#define IDS_ACTION_TOOL_ALL             4034
#define IDS_ACTION_TITLE_PATH           4035
#define IDS_ACTION_TITLE_TOOL           4036
#define IDS_FORMAT_LIST_NAME            5000
#define IDS_FORMAT_LIST_DLL             5001
#define IDS_FORMAT_LIST_HEADER          5002
#define IDS_FORMAT_LIST_COMMENT         5003
#define IDS_FORMAT_LIST_FORMAT          5004
#define IDS_FORMAT_NON_PROP             5005
#define IDS_FORMAT_COMMENT_TEXT         5006
#define IDS_FORMAT_COMMENT_BITMAP       5007
#define IDS_FORMAT_COMMENT_FILE         5008
#define IDS_FORMAT_SELECT_TITLE         5009
#define IDS_FORMAT_SELECT_MSG           5010
#define IDS_FORMAT_HEAD_SELECT_TITLE    5011
#define IDS_FORMAT_HEAD_SELECT_MSG      5012
#define IDS_FORMAT_ERR_NAME             5013
#define IDS_FILTER_LIST_NAME            6000
#define IDS_FILTER_LIST_ACTION          6001
#define IDS_FILTER_LIST_SIZE            6002
#define IDS_FILTER_ACTION_ADD           6003
#define IDS_FILTER_ACTION_ADD_NOSAVE    6004
#define IDS_FILTER_ACTION_IGNORE        6005
#define IDS_FILTER_ERR_NAME             6006
#define IDS_WINDOW_LIST_TITLE           7000
#define IDS_WINDOW_LIST_CLASSNAME       7001
#define IDS_WINDOW_LIST_IGNORE          7002
#define IDS_WINDOW_LIST_FOCUS           7003
#define IDS_WINDOW_LIST_PASTE           7004
#define IDS_WINDOW_LIST_IGNORE_ON       7005
#define IDS_WINDOW_LIST_IGNORE_OFF      7006
#define IDS_WINDOW_LIST_FOCUS_ON        7007
#define IDS_WINDOW_LIST_FOCUS_OFF       7008
#define IDS_WINDOW_LIST_PASTE_ON        7009
#define IDS_WINDOW_LIST_PASTE_OFF       7010
#define IDS_WINDOW_ERR_INPUT            7011
#define IDS_SENDKEY_LIST_TITLE          8000
#define IDS_SENDKEY_LIST_CLASSNAME      8001
#define IDS_SENDKEY_LIST_COPY           8002
#define IDS_SENDKEY_LIST_PASTE          8003
#define IDS_SENDKEY_ERR_INPUT           8004
#define IDS_TOOL_LIST_TITLE             9000
#define IDS_TOOL_LIST_DLL               9001
#define IDS_TOOL_LIST_FUNC              9002
#define IDS_TOOL_LIST_CMD_LINE          9003
#define IDS_TOOL_LIST_HOTKEY            9004
#define IDS_TOOL_SELECT_TITLE           9005
#define IDS_TOOL_SELECT_MSG             9006
#define IDS_TOOL_NON_PROP               9007
#define IDS_TOOL_ERR_TITLE              9008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
